import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: "column",
    backgroundColor: "white",
    alignItems: "center",
    justifyContent: "flex-end",
    width: "100%",
  },
  messagesContainer: {
    flex: 1,
    fontFamily: "Inter",
    fontSize: 15,
    fontWeight: 600,
    width: "100%",
    marginBottom: -30,
  },
  typingContainer: {
    flexDirection: "row",
    justifyContent: "flex-start",
    height: 40,
    width: "100%",
    paddingLeft: 9,
    marginBottom: 20,
    backgroundColor: "transparent",
  },
  typingIcon: {
    backgroundColor: "lightgray",
    borderRadius: 50,
    borderWidth: 2,
    borderColor: "black",
    marginRight: -15,
  },
  typingDots: {
    fontSize: 40,
    height: 40,
    paddingLeft: 15,
    backgroundColor: "transparent",
  },
  bottomChatContainer: {
    paddingBottom: 10,
    flexDirection: "column-reverse",
    alignItems: "flex-start",
    width: "100%",
  },
  inputContainer: {
    flexDirection: "row",
    alignItems: "center",
    paddingLeft: 21,
  },
  addButton: {
    fontFamily: "SF Pro Text",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 50,
    marginRight: 12,
    height: 34,
    width: 34,
    backgroundColor: "#E8E9EB",
  },
  addText: {
    justifyContent: "center",
    alignItems: "center",
    color: "#2D8AFB",
    fontSize: 25,
    height: "100%",
  },
  chatInput: {
    fontFamily: "SF Pro",
    paddingTop: 9,
    paddingRight: 35,
    paddingBottom: 9,
    paddingLeft: 12,
    fontSize: 15,
    width: 302,
    minHeight: 36,
    maxHeight: 115,
    borderColor: "#C5C5C7",
    borderRadius: 20,
    borderWidth: 1,
    overflow: "scroll",
  },
  incognitoWrapper: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: "50%",
    position: "absolute",
    right: 14,
    bottom: 9,
    width: 20,
    height: 20,
  },
  modalButtonContainer: {
    flexDirection: "column",
    justifyContent: "center",
    marginLeft: 19,
    marginBottom: 27,
    alignSelf: "stretch",
  },
  modalChatButton: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 11,
    gap: 26,
  },
  modalIcon: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    width: 35,
    height: 35,
    borderRadius: 500,
    overflow: "hidden",
  },
  modalChatText: { fontFamily: "SF Pro", fontSize: 19, color: "#FFF" },
  audioPopupOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    zIndex: 2,
  },
  audioPopup: {
    width: 250,
    padding: 20,
    backgroundColor: "white",
    borderRadius: 15,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  audioPopupTitle: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 10,
  },
  audioButtonContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
  },
  audioButton: {
    backgroundColor: "#2D8AFB",
    padding: 10,
    borderRadius: 10,
    marginHorizontal: 5,
  },
  audioButtonText: {
    color: "white",
    fontWeight: "bold",
  },
  closePopupText: {
    marginTop: 10,
    color: "red",
    fontWeight: "bold",
  },
  recordingIndicator: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
  },
  recordingDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: "red",
    marginRight: 5,
  },
  recordingText: {
    color: "red",
    fontWeight: "bold",
  },
});

export default styles;
